# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trader.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(741, 580)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.login_frame = QtGui.QFrame(self.centralwidget)
        self.login_frame.setGeometry(QtCore.QRect(20, 20, 700, 500))
        self.login_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.login_frame.setObjectName(_fromUtf8("login_frame"))
        self.broker_c_pwd_lineEdit = QtGui.QLineEdit(self.login_frame)
        self.broker_c_pwd_lineEdit.setGeometry(QtCore.QRect(228, 280, 221, 31))
        self.broker_c_pwd_lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.broker_c_pwd_lineEdit.setObjectName(_fromUtf8("broker_c_pwd_lineEdit"))
        self.label_2 = QtGui.QLabel(self.login_frame)
        self.label_2.setGeometry(QtCore.QRect(150, 110, 72, 15))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(self.login_frame)
        self.label_5.setGeometry(QtCore.QRect(150, 290, 72, 15))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.uqer_pwd_lineEdit = QtGui.QLineEdit(self.login_frame)
        self.uqer_pwd_lineEdit.setGeometry(QtCore.QRect(218, 100, 231, 31))
        self.uqer_pwd_lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.uqer_pwd_lineEdit.setObjectName(_fromUtf8("uqer_pwd_lineEdit"))
        self.uqer_username_lineEdit = QtGui.QLineEdit(self.login_frame)
        self.uqer_username_lineEdit.setGeometry(QtCore.QRect(220, 60, 231, 31))
        self.uqer_username_lineEdit.setObjectName(_fromUtf8("uqer_username_lineEdit"))
        self.label = QtGui.QLabel(self.login_frame)
        self.label.setGeometry(QtCore.QRect(150, 70, 72, 15))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(self.login_frame)
        self.pushButton.setGeometry(QtCore.QRect(260, 430, 161, 71))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_3 = QtGui.QLabel(self.login_frame)
        self.label_3.setGeometry(QtCore.QRect(150, 210, 72, 15))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.login_frame)
        self.label_4.setGeometry(QtCore.QRect(150, 250, 72, 15))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.broker_trade_pwd_lineEdit = QtGui.QLineEdit(self.login_frame)
        self.broker_trade_pwd_lineEdit.setGeometry(QtCore.QRect(228, 240, 221, 31))
        self.broker_trade_pwd_lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.broker_trade_pwd_lineEdit.setObjectName(_fromUtf8("broker_trade_pwd_lineEdit"))
        self.broker_account_lineEdit = QtGui.QLineEdit(self.login_frame)
        self.broker_account_lineEdit.setGeometry(QtCore.QRect(228, 200, 221, 31))
        self.broker_account_lineEdit.setObjectName(_fromUtf8("broker_account_lineEdit"))
        self.label_7 = QtGui.QLabel(self.login_frame)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_6 = QtGui.QLabel(self.login_frame)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.uqer_verify_label = QtGui.QLabel(self.login_frame)
        self.uqer_verify_label.setGeometry(QtCore.QRect(450, 100, 211, 31))
        self.uqer_verify_label.setText(_fromUtf8(""))
        self.uqer_verify_label.setObjectName(_fromUtf8("uqer_verify_label"))
        self.broker_verify_label = QtGui.QLabel(self.login_frame)
        self.broker_verify_label.setGeometry(QtCore.QRect(450, 280, 221, 31))
        self.broker_verify_label.setText(_fromUtf8(""))
        self.broker_verify_label.setObjectName(_fromUtf8("broker_verify_label"))
        self.checkBox = QtGui.QCheckBox(self.login_frame)
        self.checkBox.setGeometry(QtCore.QRect(110, 340, 121, 31))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.label_2.raise_()
        self.label_5.raise_()
        self.uqer_pwd_lineEdit.raise_()
        self.uqer_username_lineEdit.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.broker_trade_pwd_lineEdit.raise_()
        self.broker_account_lineEdit.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.uqer_verify_label.raise_()
        self.broker_verify_label.raise_()
        self.broker_c_pwd_lineEdit.raise_()
        self.checkBox.raise_()
        self.table_frame = QtGui.QFrame(self.centralwidget)
        self.table_frame.setGeometry(QtCore.QRect(20, 20, 700, 500))
        self.table_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.table_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.table_frame.setObjectName(_fromUtf8("table_frame"))
        self.tableWidget = QtGui.QTableWidget(self.table_frame)
        self.tableWidget.setGeometry(QtCore.QRect(40, 60, 641, 341))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.place_order_btn = QtGui.QPushButton(self.table_frame)
        self.place_order_btn.setGeometry(QtCore.QRect(290, 430, 161, 71))
        self.place_order_btn.setObjectName(_fromUtf8("place_order_btn"))
        self.strategy_comboBox = QtGui.QComboBox(self.table_frame)
        self.strategy_comboBox.setGeometry(QtCore.QRect(70, 10, 261, 41))
        self.strategy_comboBox.setObjectName(_fromUtf8("strategy_comboBox"))
        self.label_8 = QtGui.QLabel(self.table_frame)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 72, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 600, 120, 80))
        self.widget.setObjectName(_fromUtf8("widget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.uqer_username_lineEdit, self.uqer_pwd_lineEdit)
        MainWindow.setTabOrder(self.uqer_pwd_lineEdit, self.broker_account_lineEdit)
        MainWindow.setTabOrder(self.broker_account_lineEdit, self.broker_trade_pwd_lineEdit)
        MainWindow.setTabOrder(self.broker_trade_pwd_lineEdit, self.broker_c_pwd_lineEdit)
        MainWindow.setTabOrder(self.broker_c_pwd_lineEdit, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.strategy_comboBox)
        MainWindow.setTabOrder(self.strategy_comboBox, self.place_order_btn)
        MainWindow.setTabOrder(self.place_order_btn, self.tableWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "UqerTrader", None))
        self.label_2.setText(_translate("MainWindow", "密码", None))
        self.label_5.setText(_translate("MainWindow", "通讯密码", None))
        self.label.setText(_translate("MainWindow", "用户名", None))
        self.pushButton.setText(_translate("MainWindow", "确认登陆", None))
        self.label_3.setText(_translate("MainWindow", "资金账号", None))
        self.label_4.setText(_translate("MainWindow", "交易密码", None))
        self.label_7.setText(_translate("MainWindow", "券商账户信息", None))
        self.label_6.setText(_translate("MainWindow", "优矿账户信息", None))
        self.checkBox.setText(_translate("MainWindow", "保存账户密码", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "证券代码", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "证券名称", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "买/卖", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下单数量(股)", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "信号时间", None))
        self.place_order_btn.setText(_translate("MainWindow", "确认下单", None))
        self.label_8.setText(_translate("MainWindow", "策略：", None))

